# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

# This is a very small cluster useful for running locally and for development

global:
  # number of regions that support the zeebe platform (2 for minimal multi-region setup)
  regions: 2
  # id of the region should start at 0 for easy computation. With 2 regions, you would have region 0 and 1.
  regionId: 0
  image:
    tag: latest
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

operate:
  env:
    - name: CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME
      value: "camunda_backup"
tasklist:
  env:
    - name: CAMUNDA_TASKLIST_BACKUP_REPOSITORYNAME
      value: "camunda_backup"
      
identity:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: true
  inbound:
    mode: credentials
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  env:
    - name: CAMUNDA_OPERATE_CLIENT_USERNAME
      value: demo
    - name: CAMUNDA_OPERATE_CLIENT_PASSWORD
      value: demo

zeebe:
  clusterSize: 8
  partitionCount: 8
  replicationFactor: 4
  env:
    - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
      value: "5m"
    - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
      value: "0.85"
    - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
      value: "0.87"
    - name: ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS
      value: "camunda-zeebe-0.camunda-zeebe.europe-west4-b.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.europe-west4-b.svc.cluster.local:26502, camunda-zeebe-2.camunda-zeebe.europe-west4-b.svc.cluster.local:26502, camunda-zeebe-3.camunda-zeebe.europe-west4-b.svc.cluster.local:26502, camunda-zeebe-0.camunda-zeebe.europe-west1-b.svc.cluster.local:26502, camunda-zeebe-1.camunda-zeebe.europe-west1-b.svc.cluster.local:26502, camunda-zeebe-2.camunda-zeebe.europe-west1-b.svc.cluster.local:26502, camunda-zeebe-3.camunda-zeebe.europe-west1-b.svc.cluster.local:26502"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_CLASSNAME
      value: "io.camunda.zeebe.exporter.ElasticsearchExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_URL
      value: "http://elasticsearch-master-headless.europe-west1-b.svc.cluster.local:9200"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_BULK_SIZE
      value: "1"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_INDEX_PREFIX
      value: "zeebe-record"
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  logLevel: ERROR

elasticsearch:
  enabled: true
#  imageTag: 7.17.3
  replicas: 1
  
  extraInitContainers:
    - name: install-gcs-plugin
      image: elasticsearch:7.17.10
      securityContext:
        privileged: true
      command:
        - sh
      args:
        - -c
        - |
          ./bin/elasticsearch-plugin install --batch repository-gcs
          ./bin/elasticsearch-keystore add-file -f gcs.client.default.credentials_file ./key/gcs_backup_key.json
          cp -a ./config/elasticsearch.keystore /tmp/keystore
      volumeMounts:
        - name: plugins
          mountPath: /usr/share/elasticsearch/plugins
        - name: gcs-backup-key
          mountPath: /usr/share/elasticsearch/key
        - name: keystore
          mountPath: /tmp/keystore
  extraVolumes:
    - name: plugins
      emptyDir: {}
    - name: keystore
      emptyDir: {}
    - name: gcs-backup-key
      secret:
        secretName: gcs-backup-key
  extraVolumeMounts:
    - name: plugins
      mountPath: /usr/share/elasticsearch/plugins
      readOnly: false
    - mountPath: /usr/share/elasticsearch/key
      name: gcs-backup-key
    - name: keystore
      mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
      subPath: elasticsearch.keystore
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi
